// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKaExjuH1cB-4eg_KHuo4fWL3qc6Vd1s8',
    appId: '1:558726286638:web:9baf95936cb1ba2a2d3ebf',
    messagingSenderId: '558726286638',
    projectId: 'examplewebsitetest-76169',
    authDomain: 'examplewebsitetest-76169.firebaseapp.com',
    storageBucket: 'examplewebsitetest-76169.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31429nryWCbQlqaS-7_A7iONOeICOEoM',
    appId: '1:558726286638:android:dd4e611d6d2ada502d3ebf',
    messagingSenderId: '558726286638',
    projectId: 'examplewebsitetest-76169',
    storageBucket: 'examplewebsitetest-76169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PNuD5bZl62ivdIQxwwePDIOXim9uYi4',
    appId: '1:558726286638:ios:04ef05c43251e7762d3ebf',
    messagingSenderId: '558726286638',
    projectId: 'examplewebsitetest-76169',
    storageBucket: 'examplewebsitetest-76169.appspot.com',
    iosBundleId: 'com.example.websitetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0PNuD5bZl62ivdIQxwwePDIOXim9uYi4',
    appId: '1:558726286638:ios:04ef05c43251e7762d3ebf',
    messagingSenderId: '558726286638',
    projectId: 'examplewebsitetest-76169',
    storageBucket: 'examplewebsitetest-76169.appspot.com',
    iosBundleId: 'com.example.websitetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKaExjuH1cB-4eg_KHuo4fWL3qc6Vd1s8',
    appId: '1:558726286638:web:77ecba5669f3e1382d3ebf',
    messagingSenderId: '558726286638',
    projectId: 'examplewebsitetest-76169',
    authDomain: 'examplewebsitetest-76169.firebaseapp.com',
    storageBucket: 'examplewebsitetest-76169.appspot.com',
  );
}
